// <auto-generated />
namespace AspNetMvc_Fileupload_DropzoneJs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ProductPicture_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductPicture_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "202011162322067_ProductPicture_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
